program_id = "EVMhSco8Ju8MhFQyh1wgs9hAnuKcer4s6qPUjVGG3gh3"
operators_whitelist = [
    "86KRyxmrm4QnZXdrnf4NpHDNM3hdduUyS3gXgPhZjGuY",
    "KsvX2E7pr7gikZdff8nzoH6GW8inzW9QmV2UHEx7HA3",
    "EVzqbEjXtBJF2tTrgRm7RGSLfwQAhEbMm1nRE2dSgQqu",
    "4q8UKi8h8NQdaFXDZYDyj8vdPPFP6H4XXdhkj6P3mh5k",
    "2hH5uatt1TSptNo2M5aEAKuhtTEqz2wLK1LmR4dtRja1"
]

[chain.neon]
id = 245022000
token = "NeotkgEumEkDNL1gUMq3AHLyEqvdtCZL6FdP5GPKbFb"
