program_id = "EgbRZxFRQTiZpQGinE5jT6KQq5jtVnjtLdSTkW5UTcAv"

no_update_tracking_owners = []

operators_whitelist = [
    "2Gsipy7yniskehFAccTp4ShhmdTiP8UsLWVFdxsG6ZGt",
    "2fx77qnumM3sw5duzMYod8c8xSLavE4RwJAdNdeYZpFq",
    "2wMN3y81BXQmcyihHrByDChop6qnF1UX5f4vAp8DYjVd",
    "32U3DCL5gDNqqgfHsXuVnyJSnN6WympgBuR8TThXD2FR",
    "3HXb2SsmQSaZ3MyB6g2b1BCtL8e7DcUwBjDRAytbiVrP",
    "3tsPHg5cKnJok5N9W911QFmyb8iqSaKP4fKFqXjBciCF",
    "4Pe48zv2qQRswyioywD6Ym21YvF9u57zo5cbLJDpSJnC",
    "4hsUEQrpJiFo2gfNEaZoPKvVcgWDeWWCtUNWYCHfgiMd",
    "5283XRV4NsMyyLoGcQWMMEY89eB8FgRw7VgzSKqqepCf",
    "63tpScHzNbjQAi1AgkF6jJ1qtGjVq7aB8yLT4CJm8LvE",
    "6C5nNpaV6mot83Lh7rtMpYUVFfUAVHH6nmpC96mRh8dp",
    "7WCfs1Xe6F7M3ZwGu9BjVFhBcThrBZv2wtQ5CgvnWS54",
    "7ikHZa3j4xD6s9DKpTpAxAoe4uG9NMkty5CCmU4p3iWp",
    "7sU2USEHu7wkJFLJXza3bgCNwzFN3nddDhUeVoFiXV4Y",
    "8BRoxMVsQYjpX137ptnH1kqx6vHLk2C9QQZ7hWhPwzAC",
    "8hdWEvE5zqv3LAZ5io1M4mFW55w9frmowEEnnmbaFTsK",
    "8xzLMMVwChuFo4XZAZqsz5HtVqHTcSu7CJqogebaw3nU",
    "9DdU1ufgfe5Z7EZFuJragvkfysn4FBXto9LFMmiWCsF",
    "9EaJPCqHcJvDtJTkAQWqeLj97FQpiNZiqq49hTxM3B35",
    "9JY641aUoEMPzEUng6NpSfejg8A4hKk7YQxUo6f3R744",
    "9Ro3VV9kaBj7p21XzQB3LJQfznZkkr3t7qziWKZVbKuU",
    "ABfwv3nHL6b5ogrc3LBbUDnfYrc1JGUX2DDYG4njxGhH",
    "AD3trvWBkUYoE4kBLyTP7o2Ej8aiyCFgD8Ctoi4Tejoz",
    "ANprCKGACpkSByqyQQw2J4YEq1U68ouzx49vinAug5kH",
    "As2d7rKDnw2R366tvz7FuL57T2X1y8mVyHEuVwXBA6iQ",
    "BPPwRf4Stpecjr1YyxsBDSsEnHhPM87dcbmJLMxCfNKV",
    "BcVupnAtrZXQ5SCyGa8g7BWwT9uD3TMv5e5sEqejay1",
    "Bkf59SXA5ziH4jmjKU5nZB3SZoXAVXBT2znkiotR7bcR",
    "BsXm9NVHDyqmzVB9eUHmDXWJX7M5qxcxfxqQiXxWgX9u",
    "CjepUsoZ39xjtsMaF2mjV27AKAMMQ2AXbY6naWxLfEb6",
    "CsWCnfXuibRmz6QM6HNqh5agLshMZV1utMrBPCRhcpZk",
    "CzdHFcdazNAbJoKJeJWH9fJPNP2sbdSztQgrxs94u6Ps",
    "D9iXY6KVBJtddGCd3fghMw8ik5jEet1rVR2bmTeKDJrC",
    "DQzhkXK6DLYTbAXMFdZf3PeNX8o6nLJpHb526S7KjqXL",
    "DhorUW7jUiFTeDTSZvp5F3e22nEBQWg6Pf411366SmtG",
    "DpdcebJnjPHwMkzDconJi95o7MDQ2kY1e1Lqwk4k9fyE",
    "EW5b5UG5Wp6dL5qvvqV9aJTYN7xYis429f7yU16gezPG",
    "EaNNJzeyGpcQXAv43JHFkLQD3sKxHL7s3JAbsyJEvtwp",
    "EoqWxp9iCzo1VGs6C6awGLrmz5hQCRKeumg4NpciQCiA",
    "F2KvM8yD2epCjmh6dgzfUs1RNZ1nZV4Jbcufupq1Ex5r",
    "F4NJurNwkT7pcdvsNgCwHyJWghwBEcRiab2796QFsMG6",
    "FCzSWq6W4DZzqsXHVD85Ugt3WRtqspT2ZVxEphuD3Ege",
    "FNvRosMS9PtEUiyGZNg6gjbw7u77wc14C8P44aRj9vKr",
    "FSW7SmbZ8aqbJXgeg3SMC93ZvauGnmVmyGxgoucXqP7a",
    "GdcR94SPum5uT4iDqp19GmjNtLZaxHWb4Ex1rDFK6Jjo",
    "H9Nx2pc4eXNTXjiz8x1Sah9WD1SHzeF7u2yUdZuwmDTm",
    "HKpXxXf2LDPdcuiEjDVnRMZHXXXCcbW8RmQHByGzHVgE",
    "HX5Lv4XzTr4BVbmDM6t5UTxEKpjS4icrEFTufrdAygZC",
    "Hd4Yt22xxanJbf4bDwdgyQrXFGEFrGKfQpTzK1isrbTS",
    "HjSQ3GLiGF1mEXx92FQiXG67qQfaNQF7QZbstHYEouZe",
]

[chain.neon]
id = 245022950
token = "9ChfzoAfqGcrnK9c7cqQwd6MGrFqxA22Q9vLsS75hDzj"

[chain.sol]
id = 245022951
token = "So11111111111111111111111111111111111111112"